bank_marketing:
  target: dev
  outputs:
    dev:
      dataset: final_project
      fixed_retries: 1
      keyfile: /opt/airflow/dbt/bank_marketing/service-account.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: gold-episode-394309
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: final_project
      fixed_retries: 1
      keyfile: /opt/airflow/dbt/bank_marketing/service-account.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: gold-episode-394309
      threads: 4
      timeout_seconds: 300
      type: bigquery
  
