marketing_dwh:
  outputs:
    dev:
      dataset: final_project
      fixed_retries: 1
      keyfile: /opt/airflow/service-account.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: snappy-lattice-393408
      threads: 4
      timeout_seconds: 300
      type: bigquery
    prod:
      dataset: final_project
      fixed_retries: 1
      keyfile: /opt/airflow/service-account.json
      location: asia-southeast2
      method: service-account
      priority: interactive
      project: snappy-lattice-393408
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
